### ISSUE TITLE
Upgrade to PyTorch 0.2.0

### ISSUE THREAD

**Issue by maciejkula** [maciejkula/spotlight#37]

**Comment by EthanRosenthal** [comment]
Main bug I've found so far has been due to the fact that PyTorch 0.2.0 automatically squeezes dimensions after calls to things like `sum`. This happens on the predict function [here](https://github.com/maciejkula/spotlight/blob/master/spotlight/factorization/representations.py#L72). Easiest solution seems to be modifying it to read as

```python
dot = (user_embedding * item_embedding).sum(dim=1, keepdim=True)
```

However, even after doing that, it looks like tests are still failing due to higher error than expected. Not sure why?

**Comment by maciejkula** [comment]
I'm working the bugs out right now. I'll make a PR shortly, I'll ping you there.

**Comment by nonamestreet** [comment]
See also #24
